# Generated by Django 5.2.13 on 2026-05-08 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_staffapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffapplication',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffapplication',
            name='reason',
        ),
        migrations.AddField(
            model_name='staffapplication',
            name='motivation',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
