# Generated by Django 5.2.13 on 2026-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department_remove_user_is_campus_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('staff', 'Kulüp / Akademisyen'), ('admin', 'Sistem Yöneticisi')], default='student', max_length=10),
        ),
    ]
